name: Radar ZapID

on:
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 15 * * *'
    - cron: '0 21 * * *'
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  call-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Call Radar Endpoint
        run: curl https://zapid-cdu7.onrender.com/radar
